version: "3"

services:
  django-backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: django-backend
    env_file:
      - .env
    command:
      - bash
      - -c
      - |
        python manage.py migrate
        echo yes | python manage.py collectstatic
        gunicorn payhere.wsgi:application --bind 0.0.0.0:8000
    stdin_open: true
    volumes:
      - .:/var/www/payhere
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.21
    container_name: nginx
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - django-backend