# Generated by Django 4.0.7 on 2022-08-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbooklog',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='account_books.accountbook'),
        ),
    ]
