name: Django CI/CD workflow

on: 
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '.gitignore'
      - 'README.md'
  pull_request:
    branches:
      - main
      - develop
  
jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: django-test
          MYSQL_USER: user
          MYSQL_ROOT_PASSWORD: root
        ports: 
          - 3306:3306
        options: 
          --health-cmd="mysqladmin ping" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Migrations
      run: |
        export DEBUG=1
        export SECRET_KEY=test-secret-key
        export ALLOWED_HOSTS=*
        python manage.py migrate
      env: 
        DB_ENGINE: django.db.backends.mysql
        DB_NAME: django-test
        DB_USER: root
        DB_PASSWORD: root
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
    
    - name: Run Tests
      run: |
        export DEBUG=1
        export SECRET_KEY=test-secret-key
        export ALLOWED_HOSTS=*
        coverage run manage.py test
        coverage report
      env: 
        DB_ENGINE: django.db.backends.mysql
        DB_NAME: django-test
        DB_USER: root
        DB_PASSWORD: root
        DB_HOST: 127.0.0.1
        DB_PORT: 3306