name: Send Slack Message

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '.gitignore'
      - '.dockerignore'
      - 'README.md'
  pull_request:
    branches:
      - main
      - develop 

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
    - name: send slack push message 
      if: ${{ github.event_name == 'push' }}
      uses: pasitoapasito/custom-actions@main
      with:
        args: slack
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_MESSAGE: Push Event!!

    - name: send slack pull request message 
      if: ${{ github.event_name == 'pull_request' }}
      uses: pasitoapasito/custom-actions@main
      with:
        args: slack
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_MESSAGE: PR Event!!